import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { Product } from "../interfaces/products.interface";
import productAPI from "@/lib/productsAPI";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [products, setProducts] = useState<Product[]>();
  const [newProducts, setNewProducts] = useState<Product[]>();

  useEffect(() => {
    productAPI.get("/").then(({ data, status }) => {
      setProducts(data?.products);
    });
  }, []);

  // console.log(products);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {products?.length &&
          products.map((product) => (
            <div key={product.id}>
              <h2>{product.title}</h2>
            </div>
          ))}
      </main>
    </>
  );
}
