import Head from "next/head";
import { Inter } from "next/font/google";
import React, { useEffect, useState } from "react";
import { Product } from "../interfaces/products.interface";
import productAPI from "@/lib/productsAPI";
import { Button } from "antd";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const Home: React.FC = () => {
  const [products, setProducts] = useState<Product[]>();
  const [newProducts, setNewProducts] = useState<Product[]>();

  useEffect(() => {
    productAPI.get("/").then(({ data, status }) => {
      setProducts(data?.products);
    });
  }, []);

  // console.log(products);
  return (
    <>
      <Head>
        <title>Dev-Bazar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto max-w-7xl">
        <Navbar />
      </main>
    </>
  );
};

export default Home;
